package com.ecommerce.modelo;
// Generated 24/10/2019 07:41:37 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Datospersona generated by hbm2java
 */
public class Datospersona  implements java.io.Serializable {


     private int datperid;
     private Estadosdatospersona estadosdatospersona;
     private Personas personas;
     private Tiposdatopersona tiposdatopersona;
     private String datperdescripcion;
     private Date datperfecharegistro;
     private Date datperfechainactivo;

    public Datospersona() {
    }

	
    public Datospersona(int datperid, Estadosdatospersona estadosdatospersona, Personas personas, Tiposdatopersona tiposdatopersona, String datperdescripcion, Date datperfecharegistro) {
        this.datperid = datperid;
        this.estadosdatospersona = estadosdatospersona;
        this.personas = personas;
        this.tiposdatopersona = tiposdatopersona;
        this.datperdescripcion = datperdescripcion;
        this.datperfecharegistro = datperfecharegistro;
    }
    public Datospersona(int datperid, Estadosdatospersona estadosdatospersona, Personas personas, Tiposdatopersona tiposdatopersona, String datperdescripcion, Date datperfecharegistro, Date datperfechainactivo) {
       this.datperid = datperid;
       this.estadosdatospersona = estadosdatospersona;
       this.personas = personas;
       this.tiposdatopersona = tiposdatopersona;
       this.datperdescripcion = datperdescripcion;
       this.datperfecharegistro = datperfecharegistro;
       this.datperfechainactivo = datperfechainactivo;
    }
   
    public int getDatperid() {
        return this.datperid;
    }
    
    public void setDatperid(int datperid) {
        this.datperid = datperid;
    }
    public Estadosdatospersona getEstadosdatospersona() {
        return this.estadosdatospersona;
    }
    
    public void setEstadosdatospersona(Estadosdatospersona estadosdatospersona) {
        this.estadosdatospersona = estadosdatospersona;
    }
    public Personas getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Personas personas) {
        this.personas = personas;
    }
    public Tiposdatopersona getTiposdatopersona() {
        return this.tiposdatopersona;
    }
    
    public void setTiposdatopersona(Tiposdatopersona tiposdatopersona) {
        this.tiposdatopersona = tiposdatopersona;
    }
    public String getDatperdescripcion() {
        return this.datperdescripcion;
    }
    
    public void setDatperdescripcion(String datperdescripcion) {
        this.datperdescripcion = datperdescripcion;
    }
    public Date getDatperfecharegistro() {
        return this.datperfecharegistro;
    }
    
    public void setDatperfecharegistro(Date datperfecharegistro) {
        this.datperfecharegistro = datperfecharegistro;
    }
    public Date getDatperfechainactivo() {
        return this.datperfechainactivo;
    }
    
    public void setDatperfechainactivo(Date datperfechainactivo) {
        this.datperfechainactivo = datperfechainactivo;
    }




}


