package com.ecommerce.modelo;
// Generated 24/10/2019 07:41:37 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Estadospersona generated by hbm2java
 */
public class Estadospersona  implements java.io.Serializable {


     private int estperid;
     private String estperdescripcion;
     private Date estperfechacreacion;
     private Date estperfechainactivo;
     private boolean estperactivo;
     private Set personases = new HashSet(0);

    public Estadospersona() {
    }

	
    public Estadospersona(int estperid, String estperdescripcion, Date estperfechacreacion, boolean estperactivo) {
        this.estperid = estperid;
        this.estperdescripcion = estperdescripcion;
        this.estperfechacreacion = estperfechacreacion;
        this.estperactivo = estperactivo;
    }
    public Estadospersona(int estperid, String estperdescripcion, Date estperfechacreacion, Date estperfechainactivo, boolean estperactivo, Set personases) {
       this.estperid = estperid;
       this.estperdescripcion = estperdescripcion;
       this.estperfechacreacion = estperfechacreacion;
       this.estperfechainactivo = estperfechainactivo;
       this.estperactivo = estperactivo;
       this.personases = personases;
    }
   
    public int getEstperid() {
        return this.estperid;
    }
    
    public void setEstperid(int estperid) {
        this.estperid = estperid;
    }
    public String getEstperdescripcion() {
        return this.estperdescripcion;
    }
    
    public void setEstperdescripcion(String estperdescripcion) {
        this.estperdescripcion = estperdescripcion;
    }
    public Date getEstperfechacreacion() {
        return this.estperfechacreacion;
    }
    
    public void setEstperfechacreacion(Date estperfechacreacion) {
        this.estperfechacreacion = estperfechacreacion;
    }
    public Date getEstperfechainactivo() {
        return this.estperfechainactivo;
    }
    
    public void setEstperfechainactivo(Date estperfechainactivo) {
        this.estperfechainactivo = estperfechainactivo;
    }
    public boolean isEstperactivo() {
        return this.estperactivo;
    }
    
    public void setEstperactivo(boolean estperactivo) {
        this.estperactivo = estperactivo;
    }
    public Set getPersonases() {
        return this.personases;
    }
    
    public void setPersonases(Set personases) {
        this.personases = personases;
    }




}


