package com.ecommerce.modelo;
// Generated 24/10/2019 07:41:37 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Personas generated by hbm2java
 */
public class Personas implements java.io.Serializable {

    private int perid;
    private Estadospersona estadospersona;
    private Tiposdocumento tiposdocumento;
    private Tipossexo tipossexo;
    private String pernombre1;
    private String pernombre2;
    private String perapellido1;
    private String perapellido2;
    private Date perfechacreacion;
    private String perdocumento;
    private Set usuarioses = new HashSet(0);
    private Set datospersonas = new HashSet(0);

    public Personas() {
    }

    public Personas(int perid, Estadospersona estadospersona, Tiposdocumento tiposdocumento, Tipossexo tipossexo, String pernombre1, String perapellido1, String perapellido2, Date perfechacreacion, String perdocumento) {
        this.perid = perid;
        this.estadospersona = estadospersona;
        this.tiposdocumento = tiposdocumento;
        this.tipossexo = tipossexo;
        this.pernombre1 = pernombre1;
        this.perapellido1 = perapellido1;
        this.perapellido2 = perapellido2;
        this.perfechacreacion = perfechacreacion;
        this.perdocumento = perdocumento;
    }

    public Personas(int perid, Estadospersona estadospersona, Tiposdocumento tiposdocumento, Tipossexo tipossexo, String pernombre1, String pernombre2, String perapellido1, String perapellido2, Date perfechacreacion, String perdocumento, Set usuarioses, Set datospersonas) {
        this.perid = perid;
        this.estadospersona = estadospersona;
        this.tiposdocumento = tiposdocumento;
        this.tipossexo = tipossexo;
        this.pernombre1 = pernombre1;
        this.pernombre2 = pernombre2;
        this.perapellido1 = perapellido1;
        this.perapellido2 = perapellido2;
        this.perfechacreacion = perfechacreacion;
        this.perdocumento = perdocumento;
        this.usuarioses = usuarioses;
        this.datospersonas = datospersonas;
    }

    public int getPerid() {
        return this.perid;
    }

    public void setPerid(int perid) {
        this.perid = perid;
    }

    public Estadospersona getEstadospersona() {
        return this.estadospersona;
    }

    public void setEstadospersona(Estadospersona estadospersona) {
        this.estadospersona = estadospersona;
    }

    public Tiposdocumento getTiposdocumento() {
        return this.tiposdocumento;
    }

    public void setTiposdocumento(Tiposdocumento tiposdocumento) {
        this.tiposdocumento = tiposdocumento;
    }

    public Tipossexo getTipossexo() {
        return this.tipossexo;
    }

    public void setTipossexo(Tipossexo tipossexo) {
        this.tipossexo = tipossexo;
    }

    public String getPernombre1() {
        return this.pernombre1;
    }

    public void setPernombre1(String pernombre1) {
        this.pernombre1 = pernombre1;
    }

    public String getPernombre2() {
        return this.pernombre2;
    }

    public void setPernombre2(String pernombre2) {
        this.pernombre2 = pernombre2;
    }

    public String getPerapellido1() {
        return this.perapellido1;
    }

    public void setPerapellido1(String perapellido1) {
        this.perapellido1 = perapellido1;
    }

    public String getPerapellido2() {
        return this.perapellido2;
    }

    public void setPerapellido2(String perapellido2) {
        this.perapellido2 = perapellido2;
    }

    public Date getPerfechacreacion() {
        return this.perfechacreacion;
    }

    public void setPerfechacreacion(Date perfechacreacion) {
        this.perfechacreacion = perfechacreacion;
    }

    public String getPerdocumento() {
        return this.perdocumento;
    }

    public void setPerdocumento(String perdocumento) {
        this.perdocumento = perdocumento;
    }

    public Set getUsuarioses() {
        return this.usuarioses;
    }

    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }

    public Set getDatospersonas() {
        return this.datospersonas;
    }

    public void setDatospersonas(Set datospersonas) {
        this.datospersonas = datospersonas;
    }

}
