package com.ecommerce.modelo;
// Generated 24/10/2019 07:41:37 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private int rolid;
     private char roldesccripcion;
     private Date rolfechacreacion;
     private Date rolfechainactivo;
     private Boolean rolactivo;
     private Set usuarioses = new HashSet(0);

    public Roles() {
    }

	
    public Roles(int rolid, char roldesccripcion, Date rolfechacreacion, Date rolfechainactivo) {
        this.rolid = rolid;
        this.roldesccripcion = roldesccripcion;
        this.rolfechacreacion = rolfechacreacion;
        this.rolfechainactivo = rolfechainactivo;
    }
    public Roles(int rolid, char roldesccripcion, Date rolfechacreacion, Date rolfechainactivo, Boolean rolactivo, Set usuarioses) {
       this.rolid = rolid;
       this.roldesccripcion = roldesccripcion;
       this.rolfechacreacion = rolfechacreacion;
       this.rolfechainactivo = rolfechainactivo;
       this.rolactivo = rolactivo;
       this.usuarioses = usuarioses;
    }
   
    public int getRolid() {
        return this.rolid;
    }
    
    public void setRolid(int rolid) {
        this.rolid = rolid;
    }
    public char getRoldesccripcion() {
        return this.roldesccripcion;
    }
    
    public void setRoldesccripcion(char roldesccripcion) {
        this.roldesccripcion = roldesccripcion;
    }
    public Date getRolfechacreacion() {
        return this.rolfechacreacion;
    }
    
    public void setRolfechacreacion(Date rolfechacreacion) {
        this.rolfechacreacion = rolfechacreacion;
    }
    public Date getRolfechainactivo() {
        return this.rolfechainactivo;
    }
    
    public void setRolfechainactivo(Date rolfechainactivo) {
        this.rolfechainactivo = rolfechainactivo;
    }
    public Boolean getRolactivo() {
        return this.rolactivo;
    }
    
    public void setRolactivo(Boolean rolactivo) {
        this.rolactivo = rolactivo;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }




}


