package com.ecommerce.modelo;
// Generated 24/10/2019 07:41:37 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tiposdatopersona generated by hbm2java
 */
public class Tiposdatopersona  implements java.io.Serializable {


     private int tipdatperid;
     private String tipdatperdescripcion;
     private boolean tipdatperobligatorio;
     private Date tipdatperfecharegisto;
     private Date tipdatperfechainactivo;
     private boolean tipdatperactivo;
     private Set datospersonas = new HashSet(0);

    public Tiposdatopersona() {
    }

	
    public Tiposdatopersona(int tipdatperid, String tipdatperdescripcion, boolean tipdatperobligatorio, Date tipdatperfecharegisto, boolean tipdatperactivo) {
        this.tipdatperid = tipdatperid;
        this.tipdatperdescripcion = tipdatperdescripcion;
        this.tipdatperobligatorio = tipdatperobligatorio;
        this.tipdatperfecharegisto = tipdatperfecharegisto;
        this.tipdatperactivo = tipdatperactivo;
    }
    public Tiposdatopersona(int tipdatperid, String tipdatperdescripcion, boolean tipdatperobligatorio, Date tipdatperfecharegisto, Date tipdatperfechainactivo, boolean tipdatperactivo, Set datospersonas) {
       this.tipdatperid = tipdatperid;
       this.tipdatperdescripcion = tipdatperdescripcion;
       this.tipdatperobligatorio = tipdatperobligatorio;
       this.tipdatperfecharegisto = tipdatperfecharegisto;
       this.tipdatperfechainactivo = tipdatperfechainactivo;
       this.tipdatperactivo = tipdatperactivo;
       this.datospersonas = datospersonas;
    }
   
    public int getTipdatperid() {
        return this.tipdatperid;
    }
    
    public void setTipdatperid(int tipdatperid) {
        this.tipdatperid = tipdatperid;
    }
    public String getTipdatperdescripcion() {
        return this.tipdatperdescripcion;
    }
    
    public void setTipdatperdescripcion(String tipdatperdescripcion) {
        this.tipdatperdescripcion = tipdatperdescripcion;
    }
    public boolean isTipdatperobligatorio() {
        return this.tipdatperobligatorio;
    }
    
    public void setTipdatperobligatorio(boolean tipdatperobligatorio) {
        this.tipdatperobligatorio = tipdatperobligatorio;
    }
    public Date getTipdatperfecharegisto() {
        return this.tipdatperfecharegisto;
    }
    
    public void setTipdatperfecharegisto(Date tipdatperfecharegisto) {
        this.tipdatperfecharegisto = tipdatperfecharegisto;
    }
    public Date getTipdatperfechainactivo() {
        return this.tipdatperfechainactivo;
    }
    
    public void setTipdatperfechainactivo(Date tipdatperfechainactivo) {
        this.tipdatperfechainactivo = tipdatperfechainactivo;
    }
    public boolean isTipdatperactivo() {
        return this.tipdatperactivo;
    }
    
    public void setTipdatperactivo(boolean tipdatperactivo) {
        this.tipdatperactivo = tipdatperactivo;
    }
    public Set getDatospersonas() {
        return this.datospersonas;
    }
    
    public void setDatospersonas(Set datospersonas) {
        this.datospersonas = datospersonas;
    }




}


