package com.ecommerce.modelo;
// Generated 24/10/2019 07:41:37 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tiposdocumento generated by hbm2java
 */
public class Tiposdocumento  implements java.io.Serializable {


     private int tipdocid;
     private String tipdocdescripcion;
     private String tipdocalias;
     private Date tipdocfechacreacion;
     private Date tipdocfechainactivo;
     private boolean tipdocactivo;
     private Set personases = new HashSet(0);

    public Tiposdocumento() {
    }

	
    public Tiposdocumento(int tipdocid, String tipdocdescripcion, String tipdocalias, Date tipdocfechacreacion, boolean tipdocactivo) {
        this.tipdocid = tipdocid;
        this.tipdocdescripcion = tipdocdescripcion;
        this.tipdocalias = tipdocalias;
        this.tipdocfechacreacion = tipdocfechacreacion;
        this.tipdocactivo = tipdocactivo;
    }
    public Tiposdocumento(int tipdocid, String tipdocdescripcion, String tipdocalias, Date tipdocfechacreacion, Date tipdocfechainactivo, boolean tipdocactivo, Set personases) {
       this.tipdocid = tipdocid;
       this.tipdocdescripcion = tipdocdescripcion;
       this.tipdocalias = tipdocalias;
       this.tipdocfechacreacion = tipdocfechacreacion;
       this.tipdocfechainactivo = tipdocfechainactivo;
       this.tipdocactivo = tipdocactivo;
       this.personases = personases;
    }
   
    public int getTipdocid() {
        return this.tipdocid;
    }
    
    public void setTipdocid(int tipdocid) {
        this.tipdocid = tipdocid;
    }
    public String getTipdocdescripcion() {
        return this.tipdocdescripcion;
    }
    
    public void setTipdocdescripcion(String tipdocdescripcion) {
        this.tipdocdescripcion = tipdocdescripcion;
    }
    public String getTipdocalias() {
        return this.tipdocalias;
    }
    
    public void setTipdocalias(String tipdocalias) {
        this.tipdocalias = tipdocalias;
    }
    public Date getTipdocfechacreacion() {
        return this.tipdocfechacreacion;
    }
    
    public void setTipdocfechacreacion(Date tipdocfechacreacion) {
        this.tipdocfechacreacion = tipdocfechacreacion;
    }
    public Date getTipdocfechainactivo() {
        return this.tipdocfechainactivo;
    }
    
    public void setTipdocfechainactivo(Date tipdocfechainactivo) {
        this.tipdocfechainactivo = tipdocfechainactivo;
    }
    public boolean isTipdocactivo() {
        return this.tipdocactivo;
    }
    
    public void setTipdocactivo(boolean tipdocactivo) {
        this.tipdocactivo = tipdocactivo;
    }
    public Set getPersonases() {
        return this.personases;
    }
    
    public void setPersonases(Set personases) {
        this.personases = personases;
    }




}


