package com.ecommerce.modelo;
// Generated 24/10/2019 07:41:37 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tipossexo generated by hbm2java
 */
public class Tipossexo  implements java.io.Serializable {


     private int tipsexid;
     private String tipsexdescripcion;
     private String tipsexalis;
     private Date tipsexfechacreacion;
     private Date tipsexfechainactivo;
     private boolean tipsexactivo;
     private Set personases = new HashSet(0);

    public Tipossexo() {
    }

	
    public Tipossexo(int tipsexid, String tipsexdescripcion, String tipsexalis, Date tipsexfechacreacion, boolean tipsexactivo) {
        this.tipsexid = tipsexid;
        this.tipsexdescripcion = tipsexdescripcion;
        this.tipsexalis = tipsexalis;
        this.tipsexfechacreacion = tipsexfechacreacion;
        this.tipsexactivo = tipsexactivo;
    }
    public Tipossexo(int tipsexid, String tipsexdescripcion, String tipsexalis, Date tipsexfechacreacion, Date tipsexfechainactivo, boolean tipsexactivo, Set personases) {
       this.tipsexid = tipsexid;
       this.tipsexdescripcion = tipsexdescripcion;
       this.tipsexalis = tipsexalis;
       this.tipsexfechacreacion = tipsexfechacreacion;
       this.tipsexfechainactivo = tipsexfechainactivo;
       this.tipsexactivo = tipsexactivo;
       this.personases = personases;
    }
   
    public int getTipsexid() {
        return this.tipsexid;
    }
    
    public void setTipsexid(int tipsexid) {
        this.tipsexid = tipsexid;
    }
    public String getTipsexdescripcion() {
        return this.tipsexdescripcion;
    }
    
    public void setTipsexdescripcion(String tipsexdescripcion) {
        this.tipsexdescripcion = tipsexdescripcion;
    }
    public String getTipsexalis() {
        return this.tipsexalis;
    }
    
    public void setTipsexalis(String tipsexalis) {
        this.tipsexalis = tipsexalis;
    }
    public Date getTipsexfechacreacion() {
        return this.tipsexfechacreacion;
    }
    
    public void setTipsexfechacreacion(Date tipsexfechacreacion) {
        this.tipsexfechacreacion = tipsexfechacreacion;
    }
    public Date getTipsexfechainactivo() {
        return this.tipsexfechainactivo;
    }
    
    public void setTipsexfechainactivo(Date tipsexfechainactivo) {
        this.tipsexfechainactivo = tipsexfechainactivo;
    }
    public boolean isTipsexactivo() {
        return this.tipsexactivo;
    }
    
    public void setTipsexactivo(boolean tipsexactivo) {
        this.tipsexactivo = tipsexactivo;
    }
    public Set getPersonases() {
        return this.personases;
    }
    
    public void setPersonases(Set personases) {
        this.personases = personases;
    }




}


