package com.ecommerce.modelo;
// Generated 24/10/2019 07:41:37 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tiposusuario generated by hbm2java
 */
public class Tiposusuario  implements java.io.Serializable {


     private int tipusuid;
     private String tipusudescripcion;
     private Date tipusufechacreacion;
     private Date tipusufechainactivo;
     private boolean tipusuactivo;
     private Set usuarioses = new HashSet(0);

    public Tiposusuario() {
    }

	
    public Tiposusuario(int tipusuid, String tipusudescripcion, Date tipusufechacreacion, boolean tipusuactivo) {
        this.tipusuid = tipusuid;
        this.tipusudescripcion = tipusudescripcion;
        this.tipusufechacreacion = tipusufechacreacion;
        this.tipusuactivo = tipusuactivo;
    }
    public Tiposusuario(int tipusuid, String tipusudescripcion, Date tipusufechacreacion, Date tipusufechainactivo, boolean tipusuactivo, Set usuarioses) {
       this.tipusuid = tipusuid;
       this.tipusudescripcion = tipusudescripcion;
       this.tipusufechacreacion = tipusufechacreacion;
       this.tipusufechainactivo = tipusufechainactivo;
       this.tipusuactivo = tipusuactivo;
       this.usuarioses = usuarioses;
    }
   
    public int getTipusuid() {
        return this.tipusuid;
    }
    
    public void setTipusuid(int tipusuid) {
        this.tipusuid = tipusuid;
    }
    public String getTipusudescripcion() {
        return this.tipusudescripcion;
    }
    
    public void setTipusudescripcion(String tipusudescripcion) {
        this.tipusudescripcion = tipusudescripcion;
    }
    public Date getTipusufechacreacion() {
        return this.tipusufechacreacion;
    }
    
    public void setTipusufechacreacion(Date tipusufechacreacion) {
        this.tipusufechacreacion = tipusufechacreacion;
    }
    public Date getTipusufechainactivo() {
        return this.tipusufechainactivo;
    }
    
    public void setTipusufechainactivo(Date tipusufechainactivo) {
        this.tipusufechainactivo = tipusufechainactivo;
    }
    public boolean isTipusuactivo() {
        return this.tipusuactivo;
    }
    
    public void setTipusuactivo(boolean tipusuactivo) {
        this.tipusuactivo = tipusuactivo;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }




}


