package com.ecommerce.modelo;
// Generated 24/10/2019 07:41:37 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

    private int usuid;
    private Estadosusuario estadosusuario;
    private Personas personas;
    private Roles roles;
    private Tiposusuario tiposusuario;
    private String usunombre;
    private String usupass;
    private Date usufechacreacion;

    public Usuarios() {
    }

    public Usuarios(int usuid, Estadosusuario estadosusuario, Personas personas, Roles roles, Tiposusuario tiposusuario, String usunombre, String usupass, Date usufechacreacion) {
        this.usuid = usuid;
        this.estadosusuario = estadosusuario;
        this.personas = personas;
        this.roles = roles;
        this.tiposusuario = tiposusuario;
        this.usunombre = usunombre;
        this.usupass = usupass;
        this.usufechacreacion = usufechacreacion;
    }

    public int getUsuid() {
        return this.usuid;
    }

    public void setUsuid(int usuid) {
        this.usuid = usuid;
    }

    public Estadosusuario getEstadosusuario() {
        return this.estadosusuario;
    }

    public void setEstadosusuario(Estadosusuario estadosusuario) {
        this.estadosusuario = estadosusuario;
    }

    public Personas getPersonas() {
        return this.personas;
    }

    public void setPersonas(Personas personas) {
        this.personas = personas;
    }

    public Roles getRoles() {
        return this.roles;
    }

    public void setRoles(Roles roles) {
        this.roles = roles;
    }

    public Tiposusuario getTiposusuario() {
        return this.tiposusuario;
    }

    public void setTiposusuario(Tiposusuario tiposusuario) {
        this.tiposusuario = tiposusuario;
    }

    public String getUsunombre() {
        return this.usunombre;
    }

    public void setUsunombre(String usunombre) {
        this.usunombre = usunombre;
    }

    public String getUsupass() {
        return this.usupass;
    }

    public void setUsupass(String usupass) {
        this.usupass = usupass;
    }

    public Date getUsufechacreacion() {
        return this.usufechacreacion;
    }

    public void setUsufechacreacion(Date usufechacreacion) {
        this.usufechacreacion = usufechacreacion;
    }

}
